exclude: [Gemfile, Gemfile.lock, LICENSE, README.md]
lsi: true
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from

title:            Nicos' Blog
description:      Where I occasionally write about stuff.
# logo:             bio-photo.jpg # site-logo.jpg
disqus_shortname: nicoskaralis
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
url:              http://localhost:4000

# Owner/author information
owner:
  name:           Nicos Karalis
  avatar:         bio-photo.jpg
  email:          nicoskaralis@me.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        NicosKaralis
  facebook:       nicoskaralis
  github:         NicosKaralis
  stackexchange:  http://stackexchange.com/users/446168/nicos-karalis
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         nicoskaralis
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://google.com/+NicosKaralis

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-23976290-4
google_verify:      B2DR1V7ybKQA-IC3H4Qz_N70YMJg--BiaA-bNybgqO4
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         9CCF0014C4F040067B107FA35CD61C65

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
#   - title: Theme Setup
#     url: /theme-setup/
  - title: NicosKaralis.me
    url: http://nicoskaralis.me
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Sao_Paulo
# future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink:   /:categories/:title/
permalink:   /:year/:month/:day/:title.html

# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
# 
#   coderay:
#     coderay_line_numbers: 
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: class
# 
# include: [".htaccess"]
# exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]